Generated from base-vm

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -52,7 +52,6 @@ jobs:
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
-      SEC_VBOX : ${{ vars.SEC_VBOX }}
       DEBUG: 1
       GH_TOKEN: ${{ secrets.GH_TOKEN }}
     steps:
@@ -203,7 +202,6 @@ jobs:
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
-      SEC_VBOX : ${{ vars.SEC_VBOX }}
       DEBUG: 1
       GH_TOKEN: ${{ secrets.GH_TOKEN }}
     steps:
@@ -354,7 +352,6 @@ jobs:
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
-      SEC_VBOX : ${{ vars.SEC_VBOX }}
       DEBUG: 1
       GH_TOKEN: ${{ secrets.GH_TOKEN }}
     steps:
@@ -487,7 +484,6 @@ jobs:
     env:
       MYTOKEN : ${{ secrets.MYTOKEN }}
       MYTOKEN2: "value2"
-      SEC_VBOX : ${{ vars.SEC_VBOX }}
       GH_TOKEN: ${{ secrets.GH_TOKEN }}
     steps:
     - uses: actions/checkout@v6
@@ -589,6 +585,67 @@ jobs:
           psrinfo -v
           echo "::memstat" | mdb -k
           echo "OK"
+
+
+
+
+
+  testerr:
+    strategy:
+      fail-fast: false
+    runs-on: ubuntu-24.04
+    name: test default error OmniOS
+    steps:
+    - uses: actions/checkout@v6
+    - name: Test in OmniOS
+      id: testerr
+      continue-on-error: true 
+      uses: vmactions/omnios-vm@290792137883b65a67f2c8661b1232bf971fa98a
+      with:
+        usesh: true
+        debug: true
+        run: |
+          echo "this is an error"
+          exit 1
+    - name: Verify that the previous step failed
+      if: steps.testerr.outcome != 'failure'
+      run: |
+        echo "The step was expected to fail, but it succeeded!"
+        exit 1
+    - name: Verify that the previous step succeeded
+      if: steps.testerr.outcome == 'failure'
+      run: |
+        echo "The step was expected to fail, and it failed!"
+        exit 0
+
+  testpass:
+    strategy:
+      fail-fast: false
+    runs-on: ubuntu-24.04
+    name: test default success OmniOS
+    steps:
+    - uses: actions/checkout@v6
+    - name: Test in OmniOS
+      id: testpass
+      continue-on-error: true 
+      uses: vmactions/omnios-vm@290792137883b65a67f2c8661b1232bf971fa98a
+      with:
+        usesh: true
+        debug: true
+        run: |
+          echo "this is a normal command"
+          exit 0
+    - name: Verify that the previous step succeeded
+      if: steps.testpass.outcome != 'success'
+      run: |
+        echo "The step was expected to succeed, but it failed!"
+        exit 1
+    - name: Verify that the previous step failed
+      if: steps.testpass.outcome == 'success'
+      run: |
+        echo "The step was expected to succeed, and it succeeded!"
+        exit 0
+
 
 
 
