Generated from base-vm

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -29,7 +29,7 @@ jobs:
     strategy:
       matrix:
         release: [ "r151046", "r151048", "r151050" , "r151052" , ""]
-        runs: [ "ubuntu-22.04", "ubuntu-24.04", "ubuntu-latest"]
+        runs: [ "ubuntu-22.04", "ubuntu-24.04"]
     runs-on: ${{ matrix.runs }}
     name: sshfs OmniOS
     env:
@@ -111,12 +111,98 @@ jobs:
           echo "::memstat" | mdb -k
           echo "OK"
 
+  testnfs:
+    strategy:
+      matrix:
+        release: [ "r151046", "r151048", "r151050" , "r151052" , ""]
+        runs: [ "ubuntu-22.04", "ubuntu-24.04"]
+    runs-on: ${{ matrix.runs }}
+    name: nfs OmniOS
+    env:
+      MYTOKEN : ${{ secrets.MYTOKEN }}
+      MYTOKEN2: "value2"
+      SEC_VBOX : ${{ secrets.SEC_VBOX }}
+      DEBUG: 1
+    steps:
+    - uses: actions/checkout@v4
+    - name: Creating Web console
+      uses: vmactions/cf-tunnel@v0
+      id: tunnel
+      with:
+        protocol: http
+        port: 8000
+    - name: Test in OmniOS
+      id: test
+      uses: vmactions/omnios-vm@4981f6dd790f0715b4c7113ded961330f27636d1
+      with:
+        envs: 'DEBUG MYTOKEN MYTOKEN2'
+        prepare: |
+          pkg  install socat
+        release: ${{ matrix.release }}
+        nat: |
+          "10022": "22"
+          "8080": "80"
+          "8443": "443"
+          udp:"8081": "80"
+        usesh: true
+        sync: nfs
+        run: |
+          ls -lah /root/work
+          tree $HOME/work/
+          if [ -z "$(ls -A $HOME/work)" ]; then
+            echo "nfs error."
+            exit 1
+          fi
+          echo "TEST_ENV=abc" >>${GITHUB_ENV}
+          if [ -n "test" ]; then
+            echo "false"
+          fi
+          if [ "test" ]; then
+            echo "test"
+          fi
+          pwd
+          ls -lah
+          whoami
+          env
+          psrinfo -vp
+          cat /etc/release
+          psrinfo -v
+          echo "::memstat" | mdb -k
+          echo "OK"
+
+    - name: Test NAT
+      run:
+        echo "TEST_ENV=$TEST_ENV"
+        [ "$TEST_ENV" = "abc" ]
+        ssh -vvv -p 10022 -i $HOME/.ssh/host.id_rsa root@localhost "uname -a;whoami;pwd"
+    - name: Test custom shell
+      shell: omnios {0}
+      run: |
+        pwd
+        cd $GITHUB_WORKSPACE;
+        pwd
+          if [ -n "test" ]; then
+            echo "false"
+          fi
+          if [ "test" ]; then
+            echo "test"
+          fi
+          pwd
+          ls -lah
+          whoami
+          env
+          psrinfo -vp
+          cat /etc/release
+          psrinfo -v
+          echo "::memstat" | mdb -k
+          echo "OK"
+
 
   test:
     strategy:
       matrix:
         release: [ "r151046", "r151048", "r151050" , "r151052" , ""]
-        runs: [ "ubuntu-22.04", "ubuntu-24.04", "ubuntu-latest"]
+        runs: [ "ubuntu-22.04", "ubuntu-24.04"]
     runs-on: ${{ matrix.runs }}
     name: OmniOS
     env:
